apiVersion: v1
kind: Pod
metadata:
  name: kafka-debug
spec:
  containers:
  - name: debug-container
    image: busybox:latest
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: kafka-data
      mountPath: /kafka-data
  volumes:
  - name: kafka-data
    persistentVolumeClaim:
      claimName: data0-kafka-0
  namespace:
  - name: egov
