apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/rewrite-target":"/services","nginx.ingress.kubernetes.io/use-regex":"true"},"creationTimestamp":"2024-05-14T06:05:48Z","generation":1,"labels":{"app":"egov-finance-dehradun"},"name":"egov-finance-dehradun","namespace":"egov","resourceVersion":"10514","uid":"621c1b91-b418-4642-b040-893620993996"},"spec":{"rules":[{"host":"doiwala-uk.nagalandhealthproject.org","http":{"paths":[{"backend":{"service":{"name":"egov-finance","port":{"number":8080}}},"path":"/services","pathType":"Prefix"}]}}],"tls":[{"hosts":["dehradun.nagalandhealthproject.org"],"secretName":"dehradun.nagalandhealthproject.org-tls-certs"}]},"status":{"loadBalancer":{"ingress":[{"hostname":"a025d92b4e2c14e1586c11fe69d1d7c9-931604477.ap-south-1.elb.amazonaws.com"}]}}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /services
    nginx.ingress.kubernetes.io/use-regex: "true"
  creationTimestamp: "2024-05-14T07:13:22Z"
  generation: 1
  labels:
    app: egov-finance-doiwala
  name: egov-finance-doiwala
  namespace: egov
  resourceVersion: "30165"
  uid: 3e4e01c0-7049-4a7c-9bf0-b1e1d3c28fff
spec:
  rules:
  - host: doiwala-uk.nagalandhealthproject.org
    http:
      paths:
      - backend:
          service:
            name: egov-finance
            port:
              number: 8080
        path: /services
        pathType: Prefix
  tls:
  - hosts:
    - doiwala-uk.nagalandhealthproject.org
    secretName: doiwala-uk.nagalandhealthproject.org-tls-certs
status:
  loadBalancer:
    ingress:
    - hostname: a025d92b4e2c14e1586c11fe69d1d7c9-931604477.ap-south-1.elb.amazonaws.com
