apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: playground
spec:
  accessModes:
   - "ReadWriteOnce"
  resources:
    requests:
        storage: "2Gi"
  storageClassName: "gp2"
